### ISSUE TITLE
Create login feature

### ISSUE THREAD

**Issue by RyGuy994** [RyGuy994/MATER#10]
Create login screen for user s to be able to connect

**Comment by zenith110** [comment]
Would we want to update the db accordingly to link to a user?

**Comment by RyGuy994** [comment]
yes please!! I know eventually I'd like the user to be in control of their own assets but then be able to share it with others users. Hope that makes sense.
asset_id
asset_name
......
asset_owner?

Something like that?

**Comment by zenith110** [comment]
That makes sense, I'll whip something within the next few days then put up a pr for feedback.

**Comment by RyGuy994** [comment]
You are awesome! Thank you for all this help. I've learned so much in just the last few PRs. You are AWESOME!
