### ISSUE TITLE
file structure

### ISSUE THREAD

**Issue by RyGuy994** [RyGuy994/MATER#16]
Create File structure:
-Static (folder)
--Assets (folder)
---Asset_ID (folder)
----Picture (file)
----Service_Attachments (Folder)
-----Serice-Attachment (file)

**Comment by RyGuy994** [comment]
re-designed to work with new blueprints

**Comment by RyGuy994** [comment]
got picture upload to work and placed in file structure. known bug = delete old picture upon upload of another picture

**Comment by RyGuy994** [comment]
bug when trying to add service attachment on the service_edit.html page:
mater2-web-1  | TypeError: uploaded_file() missing 1 required positional argument: 'asset_id'

**Comment by RyGuy994** [comment]
added files to branch to wrap up for the night. kinda stuck because I am a noob :D

**Comment by RyGuy994** [comment]
can't seem to get the logic correct for uploading files via service_edit

**Comment by RyGuy994** [comment]
@zenith110 can you take a peak at my branch #16? I can't seem to get the upload file to work and save it to the file struction.
Problem is a service_edit.html and service_edit route. I have the same code in service_add and it works perfectly. You can see where I add the a subfolder to static for assets then another subfolder with the id of the asset as the folder. exactly as above.
Create File structure:
-Static (folder) --works
--Assets (folder) --works
---Asset_ID (folder) --works
----Picture (file) --works (on asset_add and asset_edit)
----Service_Attachments (Folder) --works
-----Serice-Attachment (file) -- mixed (works on service_add NOT service_edit)


        # Handle multiple attachment uploads
        attachments = request.files.getlist('attachments')
        attachment_paths = []

        for attachment in attachments:
            if attachment:
                asset_folder = asset_folder_path(asset_id, 'service_attachments')
                os.makedirs(asset_folder, exist_ok=True)

                filename = secure_filename(attachment.filename)
                attachment_path = os.path.join(asset_folder, filename)
                attachment.save(attachment_path)
                attachment_paths.append(attachment_path)

        db.session.commit()  # commit change to DB
        
        # Attachments saved, now store the attachment filenames in the database
        for attachment_path in attachment_paths:
            new_attachment = ServiceAttachment(service_id=service.id, attachment_path=attachment_path)
            db.session.add(new_attachment)

**Comment by zenith110** [comment]
Ah, I haven't seen this till now. I'll take a look.

**Comment by zenith110** [comment]
Found the issue, the form is missing enctype="multipart/form-data" on the form tag for the post for service edit @RyGuy994. I also think moving forward, there should be a more real time communication channel opposed to Github issues.

**Comment by RyGuy994** [comment]
@zenith110 can you shoot me an email so we can work out some communication? its on my github.

**Comment by RyGuy994** [comment]
reworked file structure completed. Now the following:
-static (folder) -done
--assets (folder) -done
---asset_id (folder) -done
----asset_image (folder) -done
-----(file) -done
----service_attachments (folder) -WIP
-----service_id (folder) -WIP
------(file)-WIP
