### ISSUE TITLE
Export all Attachments

### ISSUE THREAD

**Issue by RyGuy994** [RyGuy994/MATER#17]
Export all attachments for service in zip file
Export all attachments for asset in zip file.

**Comment by zenith110** [comment]
what would the structure of the zip file be? a CSV with images, or?

**Comment by RyGuy994** [comment]
I am almost finished up with the structure and I wanted there to be an export All on the asset page that follows #16 I was going to see how much of a PITA it would be to export all images/attachments and then a csv of all the tables with the information in it

**Comment by RyGuy994** [comment]
Add the ability to zip the asset and all the files inside of the folder. File structure completed under #16
